### PR TITLE
Fix label proptype to allow number.

### PR DESCRIPTION
**Pull request by proxi**
We discussed it [here](https://github.com/Doist/reactist/pull/188#discussion_r419493977) but the conclusion was wrong: based on its usage in Twist-Web (in ConfirmDialog) the label type should also allow number as value.

### CODE REVIEW

**Comment by proxi** [comment]
Fixed to also allow undefined (as preliminary step to fix strict mode).

**Comment by proxi** [comment]
@henningmu @gnapse Just a reminder that this fix and bumping twist-web reactist version to include types will be needed to complete typing effort next week.

**Comment by gnapse** [comment]
I still maintain it can and should be a `React.ReactNode`. But I am not saying this is blocking anything, just saying.

**Comment by proxi** [comment]
@gnapse Please open a separate issue so we don't lose track of it.

**Pull request merged**
