### PR TITLE
fix: Add 4px margin to Menu's viewport positioning

### PR DESCRIPTION
**Pull request by craigcarlyle**
## Short description

Adds spacing between the viewport edge and menu edge.

## PR Checklist

-   [x] Executed `npm run validate` and made sure no errors / warnings were shown
-   [x] Updated all static build artifacts (`npm run build-all`)

## Versioning
A new release will be created after this is merged.

### CODE REVIEW

**Comment by gnapse** [comment]
I haven't tried it, but looks good on the code side. Why is it still a draft? Let me know so I can approve and try it locally as well.

**Comment by craigcarlyle** [comment]
@gnapse Just had to bump the offset and build the artifacts, should be ready for testing now 👍

**Comment by gnapse** [comment]
Why does this PR lists having 92 commits?

**Comment by gnapse** [comment]
> > Why does this PR lists having 92 commits?
> 
> It was branched from `beta` before the merge.

Can you rebase it on top of main?

**Comment by gnapse** [comment]
This was closed and re-started fresh in #602.

**Pull request closed without merging**
