### PR TITLE
Add auto-scrolling to overflowing Modal.Body

### PR DESCRIPTION
**Pull request by gnarmedia**
**Link to issue:** (when applicable)

**Short description:**

Please describe your implementation and any details that we should keep in mind during review.

**PR Checklist:**

* [ ] Added tests for bugs / new features
* [ ] Updated docs (storybooks, readme)
* [ ] Described changes in CHANGELOG.md
* [ ] Executed `npm run check` and made sure no errors / warnings were shown
* [ ] Executed `npm run test` and made sure all tests are passing
* [ ] Bumped version in package.json
* [ ] Updated all static build artifacts (`npm run build-all`)

### CODE REVIEW

**Comment by gnarmedia** [comment]
@henningmu Is there any new tests you'd like to add to this? I made a story for a scrollable body, but that's about it.

**Comment by henningmu** [comment]
Hey @gnarmedia 
just wanted to let you know this is not forgotten. Will review it first thing in the morning (CEST) and give you some feedback 👍

**Comment by gnarmedia** [comment]
Cool, thanks!

**Comment by henningmu** [comment]
Awesome change. Thank you for the contribution 🙌

The story is fine as test – not perfect but enough until we introduce proper ui testing ;)

One small thing we need to fix before the release: The modal header and actions should get a `flex-shrink: 0` so their size stays fixed.

After that you can remove the draft status and I can go in and prepare the release.

**Comment by gnarmedia** [comment]
Ok, I added the flex shrink: 0; to the header and actions.

**Pull request merged**
