### PR TITLE
Feature/strict types 3

### PR DESCRIPTION
**Pull request by vishnugopal**
This finishes the work that was continued in the previous PR and solves all type errors.

To check:

* Ensure tsconfig.json has strict: true & noImplicitAny: true 
* `npm run lint`
* `npm run type-check`
* `npm run build`

Note: the build still runs the webpack loader & generates a lib/ that can be removed once we are confident Twist & Todoist works fine with these changes.

### CODE REVIEW

**Comment by proxi** [comment]
- while we are at it, it would be valuable to enable `@typescript-eslint/no-explicit-any`. There are only a few simple violations.

- please update https://github.com/Doist/twist-web/pull/2274 so we can test against twist-web. It seems like there are some problems.

- there are a view JSDoc leftovers (search for `@param`) in ErrorMessage.tsx, Popover.tsx.

- there are a few camel-case disables that can be fixed by changing variable name: is_valid_message, refresh_interval, next_props, scrolling_parent, ...

**Comment by vishnugopal** [comment]
> * while we are at it, it would be valuable to enable `@typescript-eslint/no-explicit-any`. There are only a few simple violations.

Done!

> * please update [Doist/twist-web#2274](https://github.com/Doist/twist-web/pull/2274) so we can test against twist-web. It seems like there are some problems.

Yup, there were a few unexpected types, everything should be fixed now!

> * there are a view JSDoc leftovers (search for `@param`) in ErrorMessage.tsx, Popover.tsx.

Fixed, thanks 🙂

> * there are a few camel-case disables that can be fixed by changing variable name: is_valid_message, refresh_interval, next_props, scrolling_parent, ...

This is also done as much as possible. There are still some CSS classes used in classnames that will be too cumbersome to change now.

**Comment by vishnugopal** [comment]
Merging down to the 4.0 branch!

**Comment by gnapse** [comment]
@vishnugopal just to make sure: can we delete this branch?

**Pull request merged**
