### PR TITLE
Modal portal

### PR DESCRIPTION
**Pull request by SYGINT**
**Link to issue:** #149

**Short description:**

Please describe your implementation and any details that we should keep in mind during review.

**PR Checklist:**

* [ ] Added tests for bugs / new features
* [ ] Updated docs (storybooks, readme)
* [ ] Described changes in CHANGELOG.md
* [ ] Executed `npm run check` and made sure no errors / warnings were shown
* [ ] Executed `npm run test` and made sure all tests are passing
* [ ] Bumped version in package.json
* [ ] Updated all static build artifacts (`npm run build-all`)

### CODE REVIEW

**Comment by gnarmedia** [comment]
So I added the Portal, but it doesn't pass the tests because the Portal isn't rendering output in the tests

**Comment by gnarmedia** [comment]
https://stackoverflow.com/questions/48094581/testing-react-portals-with-enzyme

**Comment by henningmu** [comment]
Hey @gnarmedia 
just wanted to let you know this is not forgotten. Will review it first thing in the morning (CEST) and give you some feedback 👍

**Comment by henningmu** [comment]
Instead of using the auto mock from jest adapt the first line in the test file to this:
```js
jest.mock('react-dom', () => ({
    createPortal: (element, node) => element,
    unmountComponentAtNode: jest.fn()
}))
```
This will return the element when creating a portal and ensure our tests continue to work.

After that you can remove the draft flag from this PR and I go in and take care of releasing it 🙌

**Comment by gnarmedia** [comment]
Cool, thanks!

**Comment by henningmu** [comment]
Hi @gnarmedia 

I think there's still one thing missing: When closing the modal we call 
```js
ReactDOM.unmountComponentAtNode(document.getElementById('modal_box'))
```

As you see for this to work we still require the Modal to be mounted into an element with the id `modal_box`. I think as part of this PR we should adapt that as well 👍

**Comment by gnarmedia** [comment]
Sounds good, I'll work on this when I have a sec

**Comment by gnapse** [comment]
I'm closing this as stale, and possible no longer relevant, as we're introducing a re-implemented modal component (#547) which will land in beta later this week.

**Pull request closed without merging**
