### PR TITLE
refactor: Adopt @doist/eslint-config

### PR DESCRIPTION
**Pull request by proxi**
## Short description

Adopt @doist/eslint-config. WIP.

## PR Checklist

-   [ ] Added tests for bugs / new features
-   [ ] Updated docs (storybooks, readme)
-   [ ] Executed `npm run validate` and made sure no errors / warnings were shown
-   [ ] Described changes in `CHANGELOG.md`
-   [ ] Bumped version in `package.json`
-   [ ] Updated all static build artifacts (`npm run build-all`)

## Versioning

It is internal cleanup, no need to release.

### CODE REVIEW

**Comment by proxi** [comment]
@gnapse I need your help to fix or ignore remaining violations - and also review if the ignores I did make sense.

**Comment by proxi** [comment]
@Doist/frontend Could anyone help wrapping this up?

**Comment by henningmu** [comment]
Saw this and added it to my list, hope to get it in before the end of the week 🙌

**Comment by henningmu** [comment]
@proxi pushed a couple of commits to make this green, please review this before merging 👍

**Comment by proxi** [comment]
@henningmu Tests are passing and you already had a look, and Ernesto is OOO, so I'm merging without approval.

**Pull request merged**
