### PR TITLE
chore: Update all of eslint and prettier packages

### PR DESCRIPTION
**Pull request by proxi**
## Short description

Update all of eslint and prettier packages  in preparation to adopt [shared config](https://github.com/Doist/eslint-config).

## Versioning

Only affects linting, does not need publishing.

### CODE REVIEW

**Review by henningmu — APPROVED** [review]
Might clash with https://github.com/Doist/reactist/pull/356 but should be handle-able by whomever is merging in second :D

**Comment by gnapse** [comment]
I can adopt/merge these changes into #356, since that PR is ready to perform a release.

**Review by gnapse — APPROVED** [review]

**Comment by proxi** [comment]
@gnapse Whatever you feel like doing, I can also rebase this later.

BTW if you're looking for a simple way to update, I recommend 'npm-check-updates': `npx npm-check-updates -u /(eslint|prettier)/ && npm install`.

**Comment by gnapse** [comment]
> BTW if you're looking for a simple way to update, I recommend 'npm-check-updates': npx npm-check-updates -u /(eslint|prettier)/ && npm install.

Good to know. I use a different approach with a vscode extension that allows me to see the packages that could be upgraded, even taking into account semantic versioning so that I can choose to not upgrade across major version changes. But it's good to know the alternatives.

**Comment by gnapse** [comment]
> Whatever you feel like doing, I can also rebase this later.

I already made it mergeable with #356 and my plan is to merge this into that, and then use #356 to make a release. Sounds good?

**Comment by proxi** [comment]
Sure.

**Pull request merged**
